repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0  # Use the latest version
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint
          - eslint-plugin-react
          - eslint-config-react-app

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0  # Use the latest version
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, css, scss, json] 